### ISSUE TITLE
Database Stack Selection

### ISSUE THREAD

**Issue by CCorrado** [CCorrado/ssw690ossmgmt#1]
Creating an issue to discuss the technology we wish to implement the database in.

Requirements for the database:
- It should be available to deploy and consume on the web
- It should make available it's schema and interface for other developers to contribute and consume.
- It should be independent of other services.

**Comment by CCorrado** [comment]
MySQL for the Database

**Comment by CCorrado** [comment]
https://github.com/JetBrains/Exposed --- Kotlin
http://www.ntu.edu.sg/home/ehchua/programming/java/jdbc_basic.html -- Java

**Comment by CCorrado** [comment]
@Rosovski  take a look at this https://github.com/Yelp/swagger-gradle-codegen

**Comment by Rosovski** [comment]
Got it！

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
