### ISSUE TITLE
Application API tech stack selection

### ISSUE THREAD

**Issue by CCorrado** [CCorrado/ssw690ossmgmt#4]
Creating an issue to discuss our Application API technology implementation.

This API should be:
- Deployed and it's specification (i.e. Swagger, Apiary, etc) made available on the web using standard security measures (HTTPS, simple auth, etc)
- Interact and expose interfaces to all available Microservices.

**Comment by CCorrado** [comment]
https://swagger.io/tools/swagger-ui/ --> for documentation :)

**Comment by Abezzam10** [comment]
Swagger seems lit

**Comment by CCorrado** [comment]
https://itnext.io/wiring-up-an-api-server-with-express-and-swagger-9bffe0a0d6bd --> NodeJS/Javascript App API
